### ISSUE TITLE
browserify command dose not work after v7.1.0

### ISSUE THREAD

**Issue by cbmgit** [josdejong/jsoneditor#866]
I am using the light version of the jsoneditor, so I use browserify command to generate jsoneditor.js

This command works till v7.0.5 and after upgrading to v7.1.0 it does not. 

browserify ./index.js -o ./dist/cbm/jsoneditor.js -s JSONEditor -x ajv

I am seeing these errors:
Error: Cannot find module './es5-shim' from 'D:\cbmgit\jsoneditor\dist'
If run next time I see this

Error: Cannot find module './regexp' from 'D:\cbmgit\jsoneditor\dist'

Can you please chec,k is it because of 
"Upgraded to the latest version of Ace editor 1.4.6. Changed implementation
  to use `ace-builds` directly instead of `brace` (still using Ace 1.2.9)." in v7.1.0 ?

Versions I am using:
Windows 10
browserify 16.5.0
npm 6.12.1
node v12.13.1

Let me know if more information is required.

**Comment by josdejong** [comment]
Thanks for reporting. I think indeed that it is related to the switch from `brace` to `ace-builds`.

In order to be able to test this, how can I easily reproduce this issue with browserify? 

It looks like `ace-builds` cannot be used with browserify, see: https://github.com/ajaxorg/ace-builds/issues/116. The reason we switched from `brace` to `ace-builds` is that `brace` is not maintained anymore and is using a very old version of the Ace editor. Looks like there is no solution for this at this moment in time. Please let me know if anyone has an idea.

**Comment by jimmiprajapati** [comment]
It's easy to reproduce, I tried in Mac as well as on Windows. Tools needed are:
1. NPM
2. Browserify

Command to run to generate:
browserify ./index.js -o ./dist/any/jsoneditor.js -s JSONEditor -x ajv

**Comment by josdejong** [comment]
Thanks. I can reproduce the issue with this minimal setup:

Create a file index.js in the root of the JSONEditor library with the following contents:
```js
// file index.js
const JSONEditor = require('./dist/jsoneditor.js')
```
Then run browserify on the command line:
```sh
npx browserify index.js -o index.bundle.js
```
This will give the following errors as output::

```
Error: Cannot find module './regexp' from '/home/jos/Dropbox/Jos/projects/js/jsoneditor/dist'
    at /home/jos/.npm/_npx/13212/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/home/jos/.npm/_npx/13212/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/jos/.npm/_npx/13212/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/jos/.npm/_npx/13212/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqCallback.oncomplete (fs.js:158:21)
```

But again, it looks like ace-builds cannot be used with browserify, see: ajaxorg/ace-builds#116.

**Comment by cbmgit** [comment]
Thank you, I understood the issue is with ace build.

Do you know how to generate customer file using Webpack ? is it possible to update the document using Webpack instead of browserify.

Thank you.

**Comment by josdejong** [comment]
I'm not sure what you mean with creating a custom file using Webpack. Bundling the ace editor with Webpack works fine, and with Webpack you have a lot of control over what and how files are bundled or excluded or transpiled or whatever.

**Comment by cbmgit** [comment]
I will use this concept to generate. https://github.com/josdejong/jsoneditor/blob/develop/gulpfile.js#L73

**Comment by josdejong** [comment]
:+1:
